### ISSUE TITLE
Server Starting Crash 1.21.1 Fabric

### ISSUE THREAD

**Issue by suerion** [pnk2u/More-Lectern-Variants#1]
Hey, i use a lot of your MORE Mods, but on 1.21.1 the Server Crash with More-Lectern-Variants

Without the Mod it does Work. I also use a Lot of other Mods, because i recreate an new Modpack, You could look on the Log, it is not optimized yet.
[latest.log](https://github.com/user-attachments/files/16853433/latest.log)

Here is the Error:
```[20:39:27] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'lolmlv' at 'de.pnku.mlv.MoreLecternVariants'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.3.jar:?]
	at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.3-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_5614
	at de.pnku.mlv.init.MlvBlockInit.registerBlocks(MlvBlockInit.java:49) ~[MoreLecternVariants-1.6.0+1.21.1-Fabric.jar:?]
	at de.pnku.mlv.MoreLecternVariants.onInitialize(MoreLecternVariants.java:14) ~[MoreLecternVariants-1.6.0+1.21.1-Fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.3.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_5614
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.3.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at de.pnku.mlv.init.MlvBlockInit.registerBlocks(MlvBlockInit.java:49) ~[MoreLecternVariants-1.6.0+1.21.1-Fabric.jar:?]
	at de.pnku.mlv.MoreLecternVariants.onInitialize(MoreLecternVariants.java:14) ~[MoreLecternVariants-1.6.0+1.21.1-Fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.3.jar:?]
	... 7 more```

**Comment by pnk2u** [comment]
Hi, thank you so much for reporting this. I luckily was able to quickly able to identify the issue and fix it on my end. This fix is implemented in version 1.6.1 that I just uploaded. Let me know if that fixes your issue or if there is anything else. (:

**Comment by suerion** [comment]
Hey, will come back tomorow.

**Comment by suerion** [comment]
Hey, the crashe is fixed, but i had another bug found in a lot of your mods. i will open a new issue ;)

but it works fine, it is only an style issue
